import Head from 'next/head'
import './globals.css'

export const metadata = {
  title: 'Hizbullah Najihan',
  description: 'Generated by create next app',
  keywords: 'Hizzdev, hizzdev, HIZZDEV, HizzDev, Hizz Dev HIZZ DEV, hizz dev',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ scrollBehavior: 'smooth' }}>
      <Head>
        <title>{metadata.title}</title>
        <meta name="keywords" content={metadata.keywords} />
        <link rel="canonical" href="https://hizzdev.vercel.app/" />
      </Head>
      <body>{children}</body>
    </html>
  )
}
